Rename occurences of ~Then~ to ~Than~
Goltergaul/definition pull request #21
Opened 2021-12-15 13:18 UTC by erikpaperik

Fixed a recurring typo where _then_ was used instead of _that_

2021-12-15 13:40 UTC, Goltergaul commented
That was a pretty stupid naming mistake from my side :see_no_evil: 
However I'd like to avoid this renaming to be a breaking change and would propose that we keep all the old names as deprecated aliases for now

2021-12-15 13:49 UTC, Goltergaul requested changes

2021-12-15 13:49 UTC, Goltergaul commented on lib/definition/dsl/comparators.rb
> +      def GreaterThan(min_value) # rubocop:disable Style/MethodName
pls add something like this to keep backwards compatibility:

```
alias GreaterThen GreaterThan
deprecate :GreaterThen
```

`deprecate` is coming with activesupport that we have included already FYI: https://apidock.com/rails/Module/deprecate

2021-12-15 18:41 UTC, TheWudu commented
Is it already in use somewhere ? If not then i would prefer a breaking change ;-)

2021-12-16 07:44 UTC, Goltergaul commented
@maf yes it is

2021-12-16 12:49 UTC, TheWudu approved these changes

2022-01-17 09:59 UTC, Goltergaul commented
@erikpaperik do you have time to finish this pr?

2022-05-20 09:49 UTC, Goltergaul approved these changes

2022-05-20 09:52 UTC, merged